[versions]

# app config
compileSdk = "36"
minSdk = "26"
targetSdk = "35"

# plugins
agp = "8.11.2"
org-jetbrains-kotlin-android = "2.2.21"
org-jetbrains-kotlin-jvm = "2.2.21"
devtools-ksp = "2.2.20-2.0.4"

# core
core-ktx = "1.16.0"
kotlinx_immutable = "0.3.5"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
serialization = "2.0.0"

# presentation
lifecycle-runtime-ktx = "2.9.1"
coil-compose = "2.6.0"

# compose
composecompiler = "2.2.21"
activity-compose = "1.10.1"
compose-bom = "2025.06.00"
navigation = "2.9.0"


# data
androidx-room = "2.7.1"
androidx-datastore-preferences = "1.1.7"
datastore = "1.1.7"

# tests
junit = "4.13.2"
mockk = "1.13.7"
androidx-test-ext-junit = "1.2.1"
androidx-test-runner = "1.6.2"
espresso-core = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"

# dagger
dagger = "2.51.1"

#ktor
ktor = "3.3.1"

workRuntimeKtx = "2.10.3"
composeMaterialCore = "1.5.0"
composeMaterial = "1.5.2"
uiToolingPreviewAndroid = "1.9.2"
navigationCommonAndroid = "2.9.5"
runtimeAndroid = "1.9.3"



[libraries]

# core
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx_immutable" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization =  { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# data
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore-preferences"}

androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }

# presentation
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation" }

# tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }

espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

#ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization-kotlinx = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
# dagger2
dagger = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }

# navigatiom
navigation-compose = {group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation"}
navigation-fragment = {group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation"}
navigation-ui = {group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation"}
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-compose-material-core = { group = "androidx.wear.compose", name = "compose-material-core", version.ref = "composeMaterialCore" }
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-navigation-common-android = { group = "androidx.navigation", name = "navigation-common-android", version.ref = "navigationCommonAndroid" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composecompiler" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
[bundles]
